name = "problemset"
main = "src/index.js"
compatibility_date = "2026-02-08"
preview_urls = false

[assets]
directory = "public"

[[kv_namespaces]]
binding = "PROBLEMSET"
id = "e5fe2bd9cce246fc9672529d59780f64"

# npx wrangler secret put PASS_KEY
